### ISSUE TITLE
Ling2023 Conversion (Reimer-Arenkiel lab)

### ISSUE THREAD

**Issue by alessandratrapani** [catalystneuro/reimer-arenkiel-lab-to-nwb#1]
This is to organize the conversion. 
Some general resources.

1. [Conserved neural dynamics and computations across species in olfaction ]( https://www.biorxiv.org/content/10.1101/2023.04.24.538157v2)
2. [Dense Odor Coding in the Mouse Olfactory Bulb](https://icml-compbio.github.io/2023/papers/WCBICML2023_paper122.pdf)

TO-DO:

- [x] Add conversion notes (#3)
- [x] Add raw 2p imaging interface (ScanImage) (#2)
- [x] Add manual segmentation (similar to MICrONS) (#4)
- [x] Addsubject/session metadata (similar to MICrONS)(#4)
- [x] Addodor delivery stimulus (ndx-odor-metadata) (similar to MICrONS)(#4)
- [x] Add treadmill velocity  (similar to MICrONS)(#4)
- [x] Run a stub conversion for the data we have and use the inspector. (#7)
- [x] Run stubs (#7)
- [x] Run validation using inspector (#7)
- [x] Run full conversion
- [x] Run validation.
- [x] Create demos notebook (#8)
- [x] Upload the dandi
- [x] Set the requirements.
- [x] Modify the documentation in the readme. (#9)
